const spawner = require('child_process').spawn;

mvp="The MVP aims to develop a chatbot capable of real-time analysis, providing insights into supplier offerings. The final LLM (Large Language Model) assistant will help managers make informed decisions based on cost analysis, ensuring profitable deals. The first phase targets a release date of July 23rd. Technical Approach PDF Extraction: Obtain PDFs from different vendors of each supplier and extract the content. Translation: Translate the extracted data into English for internal processing. Data Structuring: Convert the data into a structured format suitable for use with a Large Language Model (LLM). Storage: Store the structured data in a vector database like MongoDB. LLM Integration: Utilize the structured data to enable the LLM to generate accurate and relevant responses through well-crafted prompts or queries. Demo: Aim to deliver a functional demo by the third week of July. Use Cases or Query Prompts Ingredient Requirement for Lasagna: Determine the required ingredients and their quantities for making 10 dishes of lasagna, along with the current rates. Supplier Rate Comparison for Pasta: Identify which supplier offers the best rates and deals for making pasta this month. Recipe and Cost Analysis for Lasagna: Retrieve the recipe for lasagna, list all necessary ingredients, and calculate the cost of preparing 20 plates for the next day. Future Prospects API Development: Provide APIs for the team to upload PDFs and perform detailed insights on historical data and various offers. Enhanced Data Analysis: Enable deeper analysis of historical data and trends to optimize procurement and cost management. This approach ensures a streamlined process for managing supplier data, facilitating better decision-making through advanced data analysis and LLM integration."
vision="Aligning more than 500 different vendors and API solutions is difficult. The current system struggles to manage 500 suppliers, each with different vendors, making it difficult to centralize and compare prices. The complexity of tracking menu costs, resource costs, price changes, and different vendors creates significant challenges. A unified platform is needed to streamline this process, allowing for the extraction and analysis of data from various vendor PDFs. This platform would store the data in a vector format to provide better insights. Nick will provide more PDFs of different vendors to run the experiment smoothly. The current system struggles to manage 500 suppliers, each with different vendors, making it difficult to centralize and compare prices."
const data_to_pass_in = vision+mvp;

console.log('Data sent to python script:', data_to_pass_in);
const python_process = spawner('python',['D:/ComputerEngineering/GP/Module1-Backlog-Generation/python scripts/main/pipeline_1_generate_user_stories.py',data_to_pass_in]);
// python_process.stdin.write(data_to_pass_in + "\n");  // Send data via stdin
// python_process.stdin.end();
python_process.stdout.on('data', (data) => {
    console.log('Data received from python script:', data.toString());
});
python_process.stderr.on('data', (data) => {
    console.error('Error from python script:', data.toString());
});
